added boilerplate code
credgenics/scheduler-service pull request #1
Opened 2023-07-20 13:53 UTC by Bashar200

2023-08-01 10:12 UTC, mehul-mittal-credgenics requested changes
Incorporate suggested changes and review the code yourself before submitting

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/agendaInit.js
> +const graceful = () => {
graceful shutdown

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/app.js
> +app.use(express.json());
understand the use cases of middleware before adding

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/error.js
> +  if (!(error instanceof ApiError)) {
handle negative case

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/error.js
> +  if (ENV === 'prod' && !err.isOperational) {
requirement for env based checks ??

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/jobs/jobs_list/triggerEvent.js
> +const axios = require('axios');
nomenclature for files

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/jobs/jobs_list/triggerEvent.js
> +) => {
don't write callback with function

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/jobs/jobs_list/triggerEvent.js
> +  agenda.define(event_name, async (job) => {
prefer async await over promises

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/logger.js
> +  level: ENV !== 'prod' ? 'info' : 'debug',
hard coded log level

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/logger.js
> +    ENV !== 'prod' ? winston.format.colorize() : winston.format.uncolorize(),
remove env based checks from every where

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/routes/index.js
> +defaultRoutes.forEach((route) => {
don't need unecessary loop

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/routes/route-controller.js
> +  createSchEvent,
remove abbrevations

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/routes/route-controller.js
> +const catchAsync = require('../utils/catchAsync');
fix nomenclature

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/routes/route-controller.js
> +const createEvent = catchAsync(async (req, res) => {
catch async can be a middleware

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/routes/route-controller.js
> +  res
res.json can be used

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/routes/route.js
> +router.get('/healthz', (req, res) => {
this route should be with base route

2023-08-01 10:12 UTC, mehul-mittal-credgenics commented on src/services/service.js
> +    const { body_ } = body;
can be reduced to lesser line

2023-08-02 04:42 UTC, Bashar200 commented on README.md
>  # scheduler-service
done

2023-08-02 04:42 UTC, Bashar200 commented on package.json
> +    "url": "git+https://github.com/Bashar200/scheduler-service.git"
done

2023-08-02 04:43 UTC, Bashar200 commented on src/agendaInit.js
> +const { Agenda } = require('@hokify/agenda');
done

2023-08-02 04:44 UTC, Bashar200 commented on src/agendaInit.js
> +agenda.maxConcurrency(10);
done

2023-08-02 05:45 UTC, Bashar200 commented on src/agendaInit.js
> +      require(`./jobs/jobs_list/${type}`)(
done

2023-08-02 05:45 UTC, Bashar200 commented on src/agendaInit.js
> +const graceful = () => {
done

2023-08-02 05:53 UTC, Bashar200 commented on src/routes/index.js
> +defaultRoutes.forEach((route) => {
done

2023-08-02 06:20 UTC, Bashar200 commented on src/services/service.js
> +    const { body_ } = body;
done

2023-08-02 06:42 UTC, Bashar200 commented on src/routes/route-controller.js
> +  createSchEvent,
done

2023-08-02 07:51 UTC, Bashar200 commented on src/logger.js
> +  level: ENV !== 'prod' ? 'info' : 'debug',
done

2023-08-02 07:51 UTC, Bashar200 commented on src/logger.js
> +    ENV !== 'prod' ? winston.format.colorize() : winston.format.uncolorize(),
done

2023-08-02 07:55 UTC, Bashar200 commented on src/routes/route.js
> +router.get('/healthz', (req, res) => {
done

2023-08-02 08:08 UTC, Bashar200 commented on src/routes/route-controller.js
> +  res
done

2023-08-02 08:41 UTC, Bashar200 commented on src/error.js
> +  if (!(error instanceof ApiError)) {
done

2023-08-02 08:41 UTC, Bashar200 commented on src/error.js
> +  if (ENV === 'prod' && !err.isOperational) {
done

2023-08-02 08:41 UTC, Bashar200 commented on src/jobs/jobs_list/triggerEvent.js
> +const axios = require('axios');
done

2023-08-02 09:55 UTC, Bashar200 commented on src/app.js
> +app.use(express.json());
done

2023-08-02 12:09 UTC, Bashar200 commented on src/jobs/jobs_list/triggerEvent.js
> +  agenda.define(event_name, async (job) => {
done

2023-08-02 12:11 UTC, Bashar200 commented on src/jobs/jobs_list/triggerEvent.js
> +) => {
done

2023-08-02 17:04 UTC, Bashar200 commented on src/routes/route-controller.js
> +const createEvent = catchAsync(async (req, res) => {
done

2023-08-03 05:30 UTC, Bashar200 commented on Dockerfile
> +FROM node:16.16.0
created ticket for the same

2023-08-03 05:45 UTC, mehul-mittal-credgenics commented
Repeated Issues

2023-08-03 05:45 UTC, closed without merging