scheduler-service
credgenics/scheduler-service pull request #2
Opened 2023-08-03 07:46 UTC by Bashar200

2023-08-03 10:49 UTC, GarvitBansal22 commented on src/routes/route.js
> +  '/fetch',
suggestion: use /get-events instead of /fetch

2023-08-03 10:51 UTC, GarvitBansal22 commented on src/routes/route.js
> +  '/create',
suggestion: use /event

2023-08-03 10:51 UTC, GarvitBansal22 commented on src/routes/route.js
> +  '/update',
suggestion: use /event instead of /update

2023-08-03 10:52 UTC, GarvitBansal22 commented on src/routes/route.js
> +  '/delete',
suggestion: use /event instead of /delete

2023-08-04 11:26 UTC, Bashar200 commented on src/routes/route.js
> +  '/create',
can use different endpoint approach

2023-08-11 13:16 UTC, mehul-mittal-credgenics commented on .eslintrc.json
> +        "no-console": 1,
it should be error level

2023-08-18 08:03 UTC, mehul-mittal-credgenics requested changes

2023-08-18 08:20 UTC, Bashar200 commented on src/jobs/jobDefinition.js
> +    logger.info(`Task API output:: ${JSON.stringify(response.data)} Event Name:: ${eventName}`);
converted to debug

2023-08-18 08:26 UTC, Bashar200 commented on src/settings.js
> +  ENV, BASE_ROUTE, SERVICE_NAME, DB_NAME, MONGO_URI, LOG_LEVEL = 'INFO', TIMEOUT_MONGO = +TIMEOUT_MONGO, PORT = +PORT, MAX_CONCURRENCY = +MAX_CONCURRENCY, MAX_POOL_SIZE = 10,
done

2023-08-18 08:37 UTC, Bashar200 commented on .eslintrc.json
> +        "no-console": 1,
done

2023-09-08 09:32 UTC, closed without merging